### ISSUE TITLE
Sequence is returning more than one element exception: MetadataToken is not unique across modules

### ISSUE THREAD

**Issue by ElanHasson** [yevhen/Orleankka#30]
*Preface*: I've been working with @yevhen on tracking down this issue and he is unable to reproduce as of yet. I can consistently reproduce with a single method on my machine.

___

In [TypedActor.cs, line 20](https://github.com/yevhen/Orleankka/blob/6c60b4ba385ef219d8cb21faa276f678ce41e5e1/Source/Orleankka/Typed/TypedActor.cs#L20):

```cs
  var member = GetType()
                .GetMembers()
                .Single(x => 
                    x.Module.MetadataToken == invocation.ModuleToken && 
                    x.MetadataToken == invocation.MemberToken);
```

The code can throw an exception with the message of "Sequence is returning more than one element exception".

Initially, the code did did not filter the members by Module.MetadataToken, as the MetaDataToken is supposed to be unique within a CLR Module. @yevhen did modify the code to filter by Module and in my case I have two methods in different modules with the same Metadatatoken for both the member and the module.

![image](https://cloud.githubusercontent.com/assets/234704/7789829/65c51eb8-023d-11e5-89a0-6d0fb3bdab99.png)

**Comment by yevhen** [comment]
Fixed by commit 019d03a980a1d70cb829357b43489264cb82525f
