### ISSUE TITLE
Support for Orleankka in Visual Studio 2015

### ISSUE THREAD

**Issue by varghesep** [yevhen/Orleankka#36]
When I build Orleankka in **Microsoft Visual Studio Enterprise 2015 RC**, I get the following error:

Unsupported

This version of Visual Studio is unable to open the following projects. The project types may not be installed or this version of Visual Studio may not support them. 

For more information on enabling these project types or otherwise migrating your assets, please see the details in the "Migration Report" displayed after clicking OK.

	 - Deployment, "C:\Temp\Orleankka-master\Orleankka-master\Source\Example.Azure.Deployment\Deployment.ccproj"

No changes required

These projects can be opened in Visual Studio 2015, Visual Studio 2013, Visual Studio 2012, and Visual Studio 2010 SP1 without changing them.
	 - Orleankka, "C:\Temp\Orleankka-master\Orleankka-master\Source\Orleankka\Orleankka.csproj"
	 - Orleankka.Tests, "C:\Temp\Orleankka-master\Orleankka-master\Source\Orleankka.Tests\Orleankka.Tests.csproj"
	 - Orleankka.Core, "C:\Temp\Orleankka-master\Orleankka-master\Source\Orleankka.Core\Orleankka.Core.csproj"
	 - TestKit, "TestKit"
	 - Orleankka.TestKit, "C:\Temp\Orleankka-master\Orleankka-master\Source\Orleankka.TestKit\Orleankka.TestKit.csproj"
	 - Orleankka.TestKit.Tests, "C:\Temp\Orleankka-master\Orleankka-master\Source\Orleankka.TestKit.Tests\Orleankka.TestKit.Tests.csproj"
	 - Demo, "Demo"
	 - FSharp, "FSharp"
	 - Demo.App, "C:\Temp\Orleankka-master\Orleankka-master\Source\Demo.App\Demo.App.csproj"
	 - Demo.App.Tests, "C:\Temp\Orleankka-master\Orleankka-master\Source\Demo.App.Tests\Demo.App.Tests.csproj"
	 - Orleankka.FSharp, "C:\Temp\Orleankka-master\Orleankka-master\Source\FSharp.Api\Orleankka.FSharp.fsproj"
	 - Orleankka.Azure, "C:\Temp\Orleankka-master\Orleankka-master\Source\Orleankka.Azure\Orleankka.Azure.csproj"
	 - Examples, "Examples"
	 - Reentrant, "C:\Temp\Orleankka-master\Orleankka-master\Source\Example.Reentrant\Reentrant.csproj"
	 - DependencyInjection, "DependencyInjection"
	 - Azure, "Azure"
	 - Serialization, "Serialization"
	 - Bond, "Bond"
	 - HttpProtocol, "HttpProtocol"
	 - Client, "C:\Temp\Orleankka-master\Orleankka-master\Source\Example.Azure.Client\Client.csproj"
	 - Cluster, "C:\Temp\Orleankka-master\Orleankka-master\Source\Example.Azure.Cluster\Cluster.csproj"
	 - Chat, "Chat"
	 - Demo, "Demo"
	 - HelloWorld, "C:\Temp\Orleankka-master\Orleankka-master\Source\FSharp.Demo.HelloWorld\HelloWorld.fsproj"
	 - Shop, "C:\Temp\Orleankka-master\Orleankka-master\Source\FSharp.Demo.Shop\Shop.fsproj"
	 - Server, "C:\Temp\Orleankka-master\Orleankka-master\Source\FSharp.Demo.Chat.Server\Server.fsproj"
	 - Client, "C:\Temp\Orleankka-master\Orleankka-master\Source\FSharp.Demo.Chat.Client\Client.fsproj"
	 - Native, "C:\Temp\Orleankka-master\Orleankka-master\Source\Example.Serialization.Native\Native.csproj"
	 - JSON, "C:\Temp\Orleankka-master\Orleankka-master\Source\Example.Serialization.JSON\JSON.csproj"
	 - EventSourcing, "EventSourcing"
	 - Idiomatic, "C:\Temp\Orleankka-master\Orleankka-master\Source\Example.EventSourcing.Idiomatic\Idiomatic.csproj"
	 - Typed, "C:\Temp\Orleankka-master\Orleankka-master\Source\Example.EventSourcing.Typed\Typed.csproj"
	 - Persistence, "Persistence"
	 - GES, "C:\Temp\Orleankka-master\Orleankka-master\Source\Example.EventSourcing.Persistence.GES\GES.csproj"
	 - Autofac, "C:\Temp\Orleankka-master\Orleankka-master\Source\Example.DependencyInjection.Autofac\Autofac.csproj"
	 - Reentrant, "C:\Temp\Orleankka-master\Orleankka-master\Source\FSharp.Demo.Reentrant\Reentrant.fsproj"
	 - Worker, "C:\Temp\Orleankka-master\Orleankka-master\Source\FSharp.Demo.Worker\Worker.fsproj"
	 - Examples, "Examples"
	 - Orleankka, "C:\Temp\Orleankka-master\Orleankka-master\Orleankka.sln"

Source\Example.Azure.Deployment\Deployment.ccproj: The application which this project type is based on was not found. Please try this link for further information: http://go.microsoft.com/fwlink/?LinkId=500718&projecttype=CC5FD16D-436D-48AD-A40C-5A424C6E3E79

**Comment by yevhen** [comment]
That's because you have newer version of Azure SDK Tools. You can either uninstall the newer version of SDK and install the one compatible with `Deployment.ccproj` (2.4) or simply unload that project if you're not intended to run Azure configuration sample locally. It has no effect on core build, it's just a sample
