### ISSUE TITLE
Don't use assembly references if not needed

### ISSUE THREAD

**Issue by varghesep** [yevhen/Orleankka#38]
I created a simple console application and added the following references. This project does not use Azure.

![err1](https://cloud.githubusercontent.com/assets/12233474/7834715/a39c7b9a-0437-11e5-8764-ef1cd1959742.PNG)

When I run the application, I get the error:

Could not load file or assembly Microsoft.WindowsAzure.Storage, Version=4.2.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35 or one of its dependencies. The system cannot find the file specified.

![err](https://cloud.githubusercontent.com/assets/12233474/7834683/584a770a-0437-11e5-9ffd-f1998555781b.PNG)

**Comment by yevhen** [comment]
That's not a problem with Orleankka but rather with Orleans. Currently, it has dependencies on Azure Storage and Configuration Manager packages.
JFYI cc: @gabikliot @sergeybykov

**Comment by gabikliot** [comment]
We have an open issue on that in Orleans: https://github.com/dotnet/orleans/issues/136
