### ISSUE TITLE
streams in playground environment.

### ISSUE THREAD

**Issue by aprooks** [yevhen/Orleankka#56]
With current configs embedded with orleankka, it is impossible to use streams in playground() environment because configs are missing. I've made a custom build with provider settings and streams are working fine. Do you want me to create PR with these changes?

**Comment by yevhen** [comment]
Do you really need to configure stream provider from xml? If no, then please take a look [here](https://github.com/yevhen/Orleankka/blob/master/Source/Orleankka.Tests/Testing/TestActions.cs#L48). I've actually thought about that and what is happening is that I give you an option to tweak default playground configs programatically.

The whole point of playground configuration is that there is no need to configure anything, no freaking configs. no stinky xml whatsoever. Just wanna play? Easy - just use playground configuration :smile:

if you want to be able to configure system by using standard Orleans configuration files (xml) but still run client and silo in the same process - use `Embedded` setup.

**Comment by aprooks** [comment]
Yes tweaking via globals did the trick. 

So the only question now if stream providers have to be enabled by default for playground or not.

**Comment by yevhen** [comment]
That's a good suggestion. I think - yes :)

**Comment by yevhen** [comment]
Ah, I've just tried it and it looks like that will require add dependency to OrleansProviders.dll to a core. Which doesn't look right :(

I'll probably need to ask guys from Orleans team to move `MemoryStorage` into a core, since it has no dependencies on Azure.
