### ISSUE TITLE
ETA for Orleans 1.0.10

### ISSUE THREAD

**Issue by mbernard** [yevhen/Orleankka#69]
Do you have any ETA for adding support of Orleans 1.0.10 and release a new nuget package of Orleankka?

**Comment by yevhen** [comment]
If there no any breaking changes in 1.10.0 then I can update to it today. I'm only concerned about bugs introduced in 1.10.0. Do you aware of any?

**Comment by yevhen** [comment]
On NuGet

**Comment by yevhen** [comment]
0.10.1
